# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "ec244bdda7f3063d1a346b3816c8b969f21a0731"

[[deps.TimeSeriesUtils]]
path = "."
uuid = "20aa821e-5b1c-4f19-affd-90757a4fca77"
version = "1.0.0-DEV"
