name = "TimeSeriesUtils"
uuid = "20aa821e-5b1c-4f19-affd-90757a4fca77"
authors = ["Mattias Villani"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
