name = "TimeSeriesUtils"
uuid = "20aa821e-5b1c-4f19-affd-90757a4fca77"
version = "1.0.0-DEV"
authors = ["Mattias Villani"]

[deps]
ARCHModels = "6d3278bc-c23a-5105-85e5-0d57d2bf684f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
ARCHModels = "2.6.1"
Distributions = "0.25.122"
FFTW = "1.10.0"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.12.0"
Plots = "1.41.2"
Polynomials = "4.1.0"
RCall = "0.14.10"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
